trigger:
  branches:
    include:
    - master
    - refs/tags/*

resources:
  repositories:
  - repository: ReleaseRepo
    type: github
    endpoint: github.com_mochamadness_oauth
    name: mochamadness/WcfService1
    ref: main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
- checkout: ReleaseRepo
- script: echo $(Build.SourceBranch) $(Build.SourceVersion)